# Generated by Django 2.1.4 on 2018-12-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("index", "0003_auto_20181211_0856")]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": (("visit_Product", "Can visit Product"),),
                "verbose_name": "产品信息",
                "verbose_name_plural": "产品信息",
            },
        )
    ]
